### ISSUE TITLE
Obtener la api de OpenAi

### ISSUE THREAD

**Issue by ruddypazd** [ASSIST-IA/.github#2]
- [ ] Url api
- [ ] api key
- [ ] curl de una solicitud api

**Comment by Andres-Cardozo84** [comment]
URL de API: https://api.openai.com/v1/chat/completions

**Comment by Andres-Cardozo84** [comment]
OPENAI_API_KEY='1111111111111'

**Comment by Andres-Cardozo84** [comment]
### **API Curl:**

curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "gpt-4o-mini",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'

----

![image](https://github.com/user-attachments/assets/8f950992-401e-45c0-a129-e854f161ffe5)

**Comment by Andres-Cardozo84** [comment]
### **Listo**

URL de la Documentacion de Open AI: https://platform.openai.com/docs/api-reference/authentication
