### ISSUE TITLE
Obtener la api de Elevenlabs

### ISSUE THREAD

**Issue by ruddypazd** [ASSIST-IA/.github#3]
- [x] Url api
- [x] api key
- [x] curl de una solicitud api

**Comment by Andres-Cardozo84** [comment]
1. Endpoint: wss://api.elevenlabs.io/v1/text-to-speech/{voice_id}/stream-input?model_id={model}

![image](https://github.com/user-attachments/assets/a853432f-37ba-4348-9426-6520235d32f0)

**Comment by Andres-Cardozo84** [comment]
2. ELEVENLABS_API_KEY='sk_7a35ab31ee448b7e1748e02373d553003cd6024d2a861670'

**Comment by Andres-Cardozo84** [comment]
3. Curl:
##Streaming Input Text:

{
  "text": "This is a sample text ",
  "voice_settings": {
    "stability": 0.8,
    "similarity_boost": 0.8
  },
  "generation_config": {
    "chunk_length_schedule": [120, 160, 250, 290]
  },
  "xi_api_key": "<XI API Key>",
  "authorization": "Bearer <Authorization Token>"
}

----

##Close Connection

{
    "text": ""
}

----

##Streaming Output Audio:

{
    "audio": "Y3VyaW91cyBtaW5kcyB0aGluayBhbGlrZSA6KQ==",
    "isFinal": false,
    "normalizedAlignment": {
        "charStartTimesMs": [0, 3, 7, 9, 11, 12, 13, 15, 17, 19, 21],
        "charDurationsMs": [3, 4, 2, 2, 1, 1, 2, 2, 2, 2, 3],
        "chars": ["H", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
    },
    "alignment": {
        "charStartTimesMs": [0, 3, 7, 9, 11, 12, 13, 15, 17, 19, 21],
        "charDurationsMs": [3, 4, 2, 2, 1, 1, 2, 2, 2, 2, 3],
        "chars": ["H", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
    }
}

----

![image](https://github.com/user-attachments/assets/ecc069f9-30de-4dbf-a430-62c4879ec8cf)
![image](https://github.com/user-attachments/assets/9cc81a4d-19b1-4086-b6a4-ee3201f5e00c)
![image](https://github.com/user-attachments/assets/b4f471bc-5b6a-4240-9ee2-528d08ba9b5f)

**Comment by Andres-Cardozo84** [comment]
### **Listo**

URL de Documentacion de ElevenLabs: https://elevenlabs.io/docs/api-reference/websockets#protocol
